PRODUCT_COPY_FILES += \
	device/xiaomi/santoni/camera/cameraserver:system/bin/cameraserver \
	device/xiaomi/santoni/camera/mm-qcamera-app:system/bin/mm-qcamera-app \
	device/xiaomi/santoni/camera/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	device/xiaomi/santoni/camera/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
	device/xiaomi/santoni/camera/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
	device/xiaomi/santoni/camera/lib/libmm-omxcore.so:system/lib/libmm-omxcore.so \
	device/xiaomi/santoni/camera/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
	device/xiaomi/santoni/camera/lib/libmorpho_memory_allocator.so:system/lib/libmorpho_memory_allocator.so \
	device/xiaomi/santoni/camera/lib/hw/camera.msm8937.so:system/lib/hw/camera.msm8937.so \
	device/xiaomi/santoni/camera/lib64/libmm-omxcore.so:system/lib64/libmm-omxcore.so \
	device/xiaomi/santoni/camera/lib64/libmorpho_memory_allocator.so:system/lib64/libmorpho_memory_allocator.so \
	device/xiaomi/santoni/camera/lib64/libmorpho_panorama.so:system/lib64/libmorpho_panorama.so \
	device/xiaomi/santoni/fingerprint/lib/hw/fingerprint.default.so:system/lib/hw/fingerprint.default.so \
	device/xiaomi/santoni/fingerprint/lib/hw/fingerprint.msm8937.so:system/lib/hw/fingerprint.msm8937.so \
	device/xiaomi/santoni/fingerprint/lib64/hw/fingerprint.default.so:system/lib64/hw/fingerprint.default.so \
	device/xiaomi/santoni/fingerprint/lib64/hw/fingerprint.fpc.so:system/lib64/hw/fingerprint.fpc.so \
	device/xiaomi/santoni/fingerprint/lib64/hw/fingerprint.goodix.so:system/lib64/hw/fingerprint.goodix.so \
	device/xiaomi/santoni/fingerprint/lib64/hw/fingerprint.msm8937.so:system/lib64/hw/fingerprint.msm8937.so \
	device/xiaomi/santoni/fingerprint/lib64/hw/gxfingerprint.default.so:system/lib64/hw/gxfingerprint.default.so \